// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prrjyforguhxcouhkzqs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBycmp5Zm9yZ3VoeGNvdWhrenFzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIyMDgzNDcsImV4cCI6MjA2Nzc4NDM0N30.OxCe5ePign2FwF-trxIJzaDGuXYoaspjy3YsmQhkc9M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});